version: 2
updates:
  - package-ecosystem: npm
    directory: /editor
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /editor/src-tauri
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
